name: Check Notebooks
on: [push, pull_request]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          disable-checks: outputs,execution_count
